sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t udemy-docker  .

script:
  - docker run -e CI=true udemy-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "udemy-docker"
  env: "UdemyDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-720830066180"
  bucket_path: "udemy-docker"
  on:
    branch: master
  access_key_id:
   secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


